---

all:
  children:
    junos:
      hosts:
        juniper-r1:
          ansible_host: 10.10.1.1
          ansible_connection: netconf
          ansible_network_os: junos
          ansible_user: ansible
    iosxr:
      hosts:
        cisco-r1:
          ansible_host: 10.10.1.99
          ansible_connection: netconf
          ansible_network_os: cisco.iosxr.iosxr
          ansible_user: ansible
